=== labbealexandre/ray-tracing/scene.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Elément racine -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- Schéma XML -->
    <xsd:element name="scene">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="params"/>
                <xsd:element ref="source" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="sphere" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="plan" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="triangle" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Élément params -->
    <xsd:element name="params">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="specular"/>
                <xsd:element ref="colors" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Elément specular -->
    <xsd:element name="specular" type="xsd:int"/>

    <!-- Elément sphere -->
    <xsd:element name="sphere">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="coords"/>
                <xsd:element ref="coord"/>
                <xsd:element ref="surface"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Elément plan -->
    <xsd:element name="plan">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="coords" minOccurs="2" maxOccurs="2"/>
                <xsd:element ref="surface"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Elément triangle -->
    <xsd:element name="triangle">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="coords" minOccurs="3" maxOccurs="3"/>
                <xsd:element ref="surface"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Élément coords -->
    <xsd:element name="coords">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="coord" minOccurs="3" maxOccurs="3"/>
            </xsd:sequence>
            <xsd:attribute name="type">
                <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="center"/>
                    <xsd:enumeration value="normal"/>
                    <xsd:enumeration value="A"/>
                    <xsd:enumeration value="B"/>
                    <xsd:enumeration value="C"/>
                </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <!-- Élément coord -->
    <xsd:element name="coord">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:float">
                    <xsd:attribute name="type" use="required">
                        <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="x"/>
                            <xsd:enumeration value="y"/>
                            <xsd:enumeration value="z"/>
                            <xsd:enumeration value="radius"/>
                        </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <!-- Élement surface -->
    <xsd:element name="surface">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="coefs" minOccurs="4" maxOccurs="4"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Élément coefs -->
    <xsd:element name="coefs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="coef" minOccurs="3" maxOccurs="3"/>
            </xsd:sequence>
            <xsd:attribute name="type">
                <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="reflexion"/>
                    <xsd:enumeration value="transmission"/>
                    <xsd:enumeration value="diffusion"/>
                    <xsd:enumeration value="specular"/>
                    <xsd:enumeration value="ambiant"/>
                </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <!-- Élément coef -->
    <xsd:element name="coef">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:float">
                    <xsd:attribute name="type" use="required">
                        <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="r"/>
                            <xsd:enumeration value="g"/>
                            <xsd:enumeration value="b"/>
                        </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <!-- Élement source -->
    <xsd:element name="source">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="coords"/>
                <xsd:element ref="colors"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Élément colors -->
    <xsd:element name="colors">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="color" minOccurs="3" maxOccurs="3"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Élément color -->
    <xsd:element name="color">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:int">
                    <xsd:attribute name="type" use="required">
                        <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="r"/>
                            <xsd:enumeration value="g"/>
                            <xsd:enumeration value="b"/>
                        </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== labbealexandre/ray-tracing/example.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd">

    <params>
        <specular>10</specular>
        <colors>
            <color type="r">0</color>
            <color type="g">0</color>
            <color type="b">0</color>
        </colors>
    </params>

    <source>
        <coords type="center">
            <coord type="x">-1000</coord>
            <coord type="y">0</coord>
            <coord type="z">100</coord>
        </coords>
        <colors>
            <color type="r">255</color>
            <color type="g">255</color>
            <color type="b">255</color>
        </colors>
    </source>

    <sphere>
        <coords type="center">
            <coord type="x">100</coord>
            <coord type="y">-20</coord>
            <coord type="z">30</coord>
        </coords>
        <coord type="radius">20</coord>
        <surface>
            <coefs type="reflexion">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="transmission">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="diffusion">
                <coef type="r">0</coef>
                <coef type="g">0.8</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="specular">
                <coef type="r">0.7</coef>
                <coef type="g">0.7</coef>
                <coef type="b">0.7</coef>
            </coefs>
        </surface>
    </sphere>

    <sphere>
        <coords type="center">
            <coord type="x">100</coord>
            <coord type="y">-20</coord>
            <coord type="z">-30</coord>
        </coords>
        <coord type="radius">20</coord>
        <surface>
            <coefs type="reflexion">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="transmission">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="diffusion">
                <coef type="r">0</coef>
                <coef type="g">0.8</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="specular">
                <coef type="r">0.7</coef>
                <coef type="g">0.7</coef>
                <coef type="b">0.7</coef>
            </coefs>
        </surface>
    </sphere>

    <sphere>
        <coords type="center">
            <coord type="x">100</coord>
            <coord type="y">50</coord>
            <coord type="z">0</coord>
        </coords>
        <coord type="radius">10</coord>
        <surface>
            <coefs type="reflexion">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="transmission">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="diffusion">
                <coef type="r">0.8</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="specular">
                <coef type="r">0.7</coef>
                <coef type="g">0.7</coef>
                <coef type="b">0.7</coef>
            </coefs>
        </surface>
    </sphere>

    <sphere>
        <coords type="center">
            <coord type="x">200</coord>
            <coord type="y">00</coord>
            <coord type="z">0</coord>
        </coords>
        <coord type="radius">120</coord>
        <surface>
            <coefs type="reflexion">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="transmission">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="diffusion">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0.8</coef>
            </coefs>
            <coefs type="specular">
                <coef type="r">0.7</coef>
                <coef type="g">0.7</coef>
                <coef type="b">0.7</coef>
            </coefs>
        </surface>
    </sphere>

    <plan>
        <coords type="center">
            <coord type="x">150</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
        <coords type="normal">
            <coord type="x">-1</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
        <surface>
            <coefs type="reflexion">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="transmission">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <coefs type="diffusion">
                <coef type="r">1</coef>
                <coef type="g">1</coef>
                <coef type="b">1</coef>
            </coefs>
            <coefs type="specular">
                <coef type="r">0</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
        </surface>
    </plan>
</scene>

=== labbealexandre/ray-tracing/scenes/PlainPolygon.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../scene.xsd">

    <params>
        <specular>15</specular>

        <coefs>
            <coef type="r">0.3</coef>
            <coef type="g">0.3</coef>
            <coef type="b">0.3</coef>
        </coefs>
    </params>

    <camera>
        <coords type="center">
            <coord type="x">0</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
        <coord type="width">15</coord>
        <coord type="height">10</coord>
        <coord type="focal">5</coord>
        <coord type="n_width">512</coord>
        <coord type="n_height">512</coord>
    </camera>

    <source>
        <coords type="center">
            <coord type="x">250</coord>
            <coord type="y">-250</coord>
            <coord type="z">250</coord>
        </coords>
        <colors>
            <color type="r">255</color>
            <color type="g">255</color>
            <color type="b">255</color>
        </colors>
    </source>
    
    <plan>
        <surface>
            <coefs>
                <coef type="r">0.6</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <texture>
                <path>./texture/blue_tile.ppm</path>
                <coords type="center">
                    <coord type="x">1000</coord>
                    <coord type="y">0</coord>
                    <coord type="z">0</coord>
                </coords>
                <coords type="direction">
                    <coord type="x">0</coord>
                    <coord type="y">1</coord>
                    <coord type="z">0</coord>
                </coords>
                <coord type="width">100</coord>
                <coord type="height">100</coord>
            </texture>
            <coef type="reflexion">0</coef>
            <coef type="transmission">0</coef>
            <coef type="diffusion">0.8</coef>
            <coef type="specular">1</coef>
        </surface>
        <coord type="n1">1</coord>
        <coord type="n2">1.3</coord>
        <coords type="center">
            <coord type="x">1000</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
        <coords type="normal">
            <coord type="x">-1</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
    </plan>

    <plan>
        <surface>
            <coefs>
                <coef type="r">0.6</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <texture>
                <path>./texture/red_tile.ppm</path>
                <coords type="center">
                    <coord type="x">-1000</coord>
                    <coord type="y">0</coord>
                    <coord type="z">0</coord>
                </coords>
                <coords type="direction">
                    <coord type="x">0</coord>
                    <coord type="y">1</coord>
                    <coord type="z">0</coord>
                </coords>
                <coord type="width">100</coord>
                <coord type="height">100</coord>
            </texture>
            <coef type="reflexion">0</coef>
            <coef type="transmission">0</coef>
            <coef type="diffusion">0.8</coef>
            <coef type="specular">1</coef>
        </surface>
        <coord type="n1">1</coord>
        <coord type="n2">1.3</coord>
        <coords type="center">
            <coord type="x">-1000</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
        <coords type="normal">
            <coord type="x">1</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
    </plan>

    <plan>
        <surface>
            <coefs>
                <coef type="r">0.6</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <texture>
                <path>./texture/tile.ppm</path>
                <coords type="center">
                    <coord type="x">0</coord>
                    <coord type="y">200</coord>
                    <coord type="z">0</coord>
                </coords>
                <coords type="direction">
                    <coord type="x">1</coord>
                    <coord type="y">0</coord>
                    <coord type="z">0</coord>
                </coords>
                <coord type="width">100</coord>
                <coord type="height">100</coord>
            </texture>
            <coef type="reflexion">0</coef>
            <coef type="transmission">0</coef>
            <coef type="diffusion">0.8</coef>
            <coef type="specular">1</coef>
        </surface>
        <coord type="n1">1</coord>
        <coord type="n2">1.3</coord>
        <coords type="center">
            <coord type="x">0</coord>
            <coord type="y">200</coord>
            <coord type="z">0</coord>
        </coords>
        <coords type="normal">
            <coord type="x">0</coord>
            <coord type="y">-1</coord>
            <coord type="z">0</coord>
        </coords>
    </plan>

    <polygon corners="5">
        <surface>
            <coefs>
                <coef type="r">1</coef>
                <coef type="g">0</coef>
                <coef type="b">0</coef>
            </coefs>
            <texture>
                <path>./texture/tile.ppm</path>
                <coords type="center">
                    <coord type="x">500</coord>
                    <coord type="y">0</coord>
                    <coord type="z">0</coord>
                </coords>
                <coords type="direction">
                    <coord type="x">0</coord>
                    <coord type="y">1</coord>
                    <coord type="z">0</coord>
                </coords>
                <coord type="width">100</coord>
                <coord type="height">100</coord>
            </texture>
            <coef type="reflexion">0</coef>
            <coef type="transmission">0</coef>
            <coef type="diffusion">1</coef>
            <coef type="specular">1</coef>
        </surface>
        <coord type="n1">1</coord>
        <coord type="n2">1.3</coord>
        <coords type="normal">
            <coord type="x">-1</coord>
            <coord type="y">0</coord>
            <coord type="z">0</coord>
        </coords>
        <coords type="corner">
            <coord type="x">200</coord>
            <coord type="y">0</coord>
            <coord type="z">100</coord>
        </coords>
        <coords type="corner">
            <coord type="x">200</coord>
            <coord type="y">-95</coord>
            <coord type="z">31</coord>
        </coords>
        <coords type="corner">
            <coord type="x">200</coord>
            <coord type="y">-59</coord>
            <coord type="z">-81</coord>
        </coords>
        <coords type="corner">
            <coord type="x">200</coord>
            <coord type="y">59</coord>
            <coord type="z">-81</coord>
        </coords>
        <coords type="corner">
            <coord type="x">200</coord>
            <coord type="y">95</coord>
            <coord type="z">31</coord>
        </coords>
    </polygon>

</scene>
